# Project Information
site_name: "LeetCode Solution"
site_author: "Weiduo Sun"
site_url: "https://WeiduoS.github.io/LeetCode"

# Repository
repo_name: "WeiduoS/LeetCode"
repo_url: "https://github.com/WeiduoS/LeetCode"
